import * as z from 'zod/v4';
import { falseBooleanSchema, optionalBooleanSchema, trueBooleanSchema } from './common.schemas';
import { ROUTERS } from '@/config/routeConfig';

export const RouteConfigSchema = z.object({
  [ROUTERS.ROOT]: optionalBooleanSchema,
  [ROUTERS.LOGIN]: optionalBooleanSchema,
  [ROUTERS.MAGIC_LINK]: optionalBooleanSchema,
  [ROUTERS.CLIENT_LOGIN]: optionalBooleanSchema,
  [ROUTERS.FORGOT_PASSWORD]: optionalBooleanSchema,
  [ROUTERS.RESET_PASSWORD]: optionalBooleanSchema,
  [ROUTERS.REGISTER]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_DASHBOARD]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_MY_TIMESHEET]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_CLOCK]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_JOBS]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_SERVICES]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_LEAVE_REQUEST]: optionalBooleanSchema,
  [ROUTERS.TIME_KEEPER_SHIFT]: optionalBooleanSchema,
  [ROUTERS.HOME]: optionalBooleanSchema,
  [ROUTERS.EXPLORE]: optionalBooleanSchema,
  [ROUTERS.MORE]: optionalBooleanSchema,
  [ROUTERS.PROFILE]: optionalBooleanSchema,
  [ROUTERS.SETTINGS]: optionalBooleanSchema,
  [ROUTERS.NOTIFICATIONS]: optionalBooleanSchema,
  [ROUTERS.CUSTOMER_CONFIG]: optionalBooleanSchema,
  [ROUTERS.PRODUCT_CONFIG]: optionalBooleanSchema,
  [ROUTERS.STORES]: optionalBooleanSchema,
  [ROUTERS.STORE_CONFIG]: optionalBooleanSchema,
  [ROUTERS.STORE_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.STORE_EDIT]: optionalBooleanSchema,
  [ROUTERS.EMPLOYEE_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.EMPLOYEE_DETAIL]: optionalBooleanSchema,
  [ROUTERS.EMPLOYEES_ADD]: optionalBooleanSchema,
  [ROUTERS.EMPLOYEE_EDIT]: optionalBooleanSchema,
  [ROUTERS.CUSTOMER_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.CUSTOMER_DETAIL]: optionalBooleanSchema,
  [ROUTERS.CUSTOMER_ADD]: optionalBooleanSchema,
  [ROUTERS.CUSTOMER_EDIT]: optionalBooleanSchema,
  [ROUTERS.PRODUCT_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.PRODUCT_DETAIL]: optionalBooleanSchema,
  [ROUTERS.PRODUCT_ADD]: optionalBooleanSchema,
  [ROUTERS.PRODUCT_EDIT]: optionalBooleanSchema,
  [ROUTERS.PO_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.PO_DETAIL]: optionalBooleanSchema,
  [ROUTERS.PO_ADD]: optionalBooleanSchema,
  [ROUTERS.PO_EDIT]: optionalBooleanSchema,
  [ROUTERS.STAFF]: optionalBooleanSchema,
  [ROUTERS.STAFF_ADD]: optionalBooleanSchema,
  [ROUTERS.STAFF_EDIT]: optionalBooleanSchema,
  [ROUTERS.USER_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.USER_DETAIL]: optionalBooleanSchema,
  [ROUTERS.ADD_USER]: optionalBooleanSchema,
  [ROUTERS.IMPORT_USERS]: optionalBooleanSchema,
  [ROUTERS.CONFIGURATION]: optionalBooleanSchema,
  [ROUTERS.SALARY_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.ROLE_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.PERMISSION_MANAGEMENT]: optionalBooleanSchema,
  [ROUTERS.ADMIN_LOGIN]: optionalBooleanSchema,
  [ROUTERS.ADMIN_DASHBOARD]: optionalBooleanSchema,
  [ROUTERS.ADMIN_CLIENTS]: optionalBooleanSchema,
  [ROUTERS.ADMIN_CLIENTS_NEW]: optionalBooleanSchema,
  [ROUTERS.ADMIN_CLIENT_DETAIL]: optionalBooleanSchema,
  [ROUTERS.ADMIN_PERMISSIONS]: optionalBooleanSchema,
  [ROUTERS.ADMIN_STORES]: optionalBooleanSchema,
  [ROUTERS.ADMIN_MONITORING]: optionalBooleanSchema,
  [ROUTERS.ADMIN_SETTINGS]: optionalBooleanSchema,
  [ROUTERS.SAMPLE_ERRORS]: optionalBooleanSchema,
  [ROUTERS.SAMPLE_ERRORS]: falseBooleanSchema,
  // true by default
  [ROUTERS.ROOT]: trueBooleanSchema,
  [ROUTERS.LOGIN]: trueBooleanSchema,
  [ROUTERS.CLIENT_LOGIN]: trueBooleanSchema,
  [ROUTERS.TIME_KEEPER_DASHBOARD]: trueBooleanSchema,
  [ROUTERS.HOME]: trueBooleanSchema,
  [ROUTERS.EXPLORE]: trueBooleanSchema,
  [ROUTERS.MORE]: trueBooleanSchema,
  [ROUTERS.PROFILE]: trueBooleanSchema,
  [ROUTERS.SETTINGS]: trueBooleanSchema,
});

// Types derived from schemas
export type RouteConfig = z.infer<typeof RouteConfigSchema>;
